version: '2.3'

services:
  chrome:
    image: justinribeiro/chrome-headless:stable
    cap_add:
      - SYS_ADMIN

  node-chrome:
    build:
      context: .
      dockerfile: docker/node-chromium.dockerfile
    volumes:
      - 'projectroot:/app'
