version: '2.3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9.3
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  chrome:
    image: justinribeiro/chrome-headless:stable
    cap_add:
      - SYS_ADMIN

  pa11y:
    build:
      context: .
      dockerfile: docker/pa11y.dockerfile
    volumes:
      - 'projectroot:/app'
