---
name: Re-setting site, for CI Tests
description: Setup Docker with caching and Buildx

inputs:
  token:
    description: A GitHub token
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        # Our Taskfile requires a proper checkout to function because of
        # certain vars.
        fetch-depth: 0
    - name: Install go-task
      uses: arduino/setup-task@v2
      with:
        repo-token: ${{ inputs.token }}
    - name: Setup site
      shell: bash
      run: task ci:reset
