# These workflows takes care of various CI tests.
on: pull_request
name: CI Tests
env:
  PHP_VERSION: 8.0
  COMPOSER_VERSION: v2

jobs:
  ValidateComposer:
    name: Validate Composer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
          tools: composer:${{ env.COMPOSER_VERSION }}
      - name: Validate composer.json
        run: |
          composer validate --no-check-all --no-check-publish

  Phpcs:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        tools: composer:${{ env.COMPOSER_VERSION }}
        coverage: none
        extensions: gd
    - name: Install Dependencies
      run: |
        composer install --no-interaction --no-progress
    - name: Run phpcs
      uses: reload/action-phpcs@main
      with:
        reviewdog_token: ${{ secrets.GITHUB_TOKEN }}

  Phpstan:
    name: Analyse code using PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
          tools: composer:${{ env.COMPOSER_VERSION }}
      - name: Install composer dependencies
        run: |
          composer install --no-interaction --no-progress
          # Add vendor/bin to PATH for subsequent steps, see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          composer config bin-dir --absolute >> "${GITHUB_PATH}"
      - name: PHPStan analyse
        run: |
          phpstan

  PhpUnit:
    name: Run PHP unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:${{ env.COMPOSER_VERSION }}
          coverage: xdebug
          extensions: gd
      - name: Install Dependencies
        run: |
          composer install --no-interaction --no-progress
      - name: Run PhpUnit
        run: ./vendor/bin/phpunit --coverage-text

  LightHouse:
    name: Test site performance using Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Our Taskfile requires a proper checkout to function because of
          # certain vars.
          fetch-depth: 0
      - name: Install go-task
        uses: arduino/setup-task@v1
      - name: Setup site
        run: task ci:reset
      - name: Run Lighthouse test
        run: task ci:lighthouse
      - name: Archive logs
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-results
          path: .lighthouseci

  Pa11y:
    name: Test accessibility using Pa11y
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Our Taskfile requires a proper checkout to function because of
          # certain vars.
          fetch-depth: 0
      - name: Install go-task
        uses: arduino/setup-task@v1
      - name: Setup site
        run: task ci:reset
      - name: Run Pa11y
        run: task ci:pa11y

  Behat:
    name: Run Behat functional tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Our Taskfile requires a proper checkout to function because of
          # certain vars.
          fetch-depth: 0
      - name: Install go-task
        uses: arduino/setup-task@v1
      - name: Setup site
        run: task ci:reset
      - name: Run Behat
        run: task ci:behat
      - name: Archive logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: behat-logs
          path: tests/behat/logs
